const resources = [
  {
    resource_name: 'dashboard',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'dashboard',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/dashboard\/[0-9]*(\/)*',
  },
  {
    resource_name: 'file',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'files',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'file',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/file\/[0-9]*(\/)*',
  },
  {
    resource_name: 'files',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/files\/[0-9]*(\/)*',
  },
  {
    resource_name: 'user',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'users',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'user',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/user\/[0-9]*(\/)*',
  },
  {
    resource_name: 'users',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/users\/[0-9]*(\/)*',
  },
  {
    resource_name: 'role',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'roles',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'role',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/role\/[0-9]*(\/)*',
  },
  {
    resource_name: 'roles',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/roles\/[0-9]*(\/)*',
  },
  {
    resource_name: 'resource',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'resources',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'resource',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/resource\/[0-9]*(\/)*',
  },
  {
    resource_name: 'resources',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/resources\/[0-9]*(\/)*',
  },
  {
    resource_name: 'search',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/search\/\?s\=[\d\D\w0-9a-zA-Z]+',
  },
  {
    resource_name: 'languages',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'language',
    resource_description: '',
    resource_type: 'view',
    resource_path: '',
  },
  {
    resource_name: 'languages',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/languages\/[0-9]*(\/)*',
  },
  {
    resource_name: 'language',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/language\/[0-9]*(\/)*',
  },
  {
    resource_name: 'profile',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/profile\/',
  },
  {
    resource_name: 'notification',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/notification\/[0-9]*(\/)*',
  },
  {
    resource_name: 'notifications',
    resource_description: '',
    resource_type: 'data',
    resource_path: '\/notifications\/[0-9]*(\/)*',
  },
]

module.exports = resources
