# Use the official image as a parent image
FROM node:alpine AS webcms-node-build

MAINTAINER eduardobc.88@gmail.com

# Set the working directory
WORKDIR /webcms/

# Run the command inside your image filesystem
RUN npm install pm2 -g
